### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-10#100]
*Congratulations on finishing milestone 3! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] One or more scripts are not well organized **- 4**

There are some problems with the scripts, namely:
- Weird blocks of empy line
- Commented out code
- Functions that could be saved in a different file and then sourced by the script.

### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to automatically update inline values generated from the analysis that are presented in the narrated text of the document but it does not work correctly or a few missing cases. **- 2**

"The reverse elbow plot \@ref(fig:elbow-plot) shows an optimal K value of 26" and others

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

- [ ] The `Makefile` is not written in a sensible order, or is disorganized, or difficult to read for some reason **- 5**

There is commented out code

### Dependencies have been updated (so it include the test libraries)

- [ ] Missing dependency. **- 1**

You are likely missing LaTeX to render the pdf

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I got an error while reproducing the analysis. **- 5**

It seems that latex is missing

```
output file: Analysis_of_Investment_Outcomes_Report.knit.md

/usr/lib/rstudio-server/bin/quarto/bin/pandoc +RTS -K512m -RTS Analysis_of_Investment_Outcomes_Report.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Analysis_of_Investment_Outcomes_Report.tex --lua-filter /usr/local/lib/R/site-library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --table-of-contents --toc-depth 2 --highlight-style tango --pdf-engine pdflatex --variable graphics --wrap preserve --variable 'geometry:margin=1in' --variable tables=yes --standalone -Mhas-frontmatter=false --citeproc
! sh: 1: pdflatex: not found

Error: LaTeX failed to compile Analysis_of_Investment_Outcomes_Report.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Analysis_of_Investment_Outcomes_Report.log for more info.
In addition: Warning message:
In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  error in running command
Execution halted
make: *** [Makefile:63: doc/Analysis_of_Investment_Outcomes_Report.pdf] Error 1
```
