### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-10#101]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Addressed feedback given by the teaching team from milestone 1

- [ ] There are no instructions linking the feedback to the changes in the source code. **- 5**

### Addressed feedback given by the teaching team from milestone 2

- [ ] There are no instructions linking the feedback to the changes in the source code. **- 5**

- [ ] 10% or less of the feedback given by the teaching team from milestone 2 was not addressed **-2.5**

### Dependencies have been updated (so it include the newly created external software package)

- [ ] Dependencies have been updated but are not in the final image. **- 0.5**

### Project file and directory structure organization

- [ ] There are incorrect file and directory structure. For instance, missing README, license, code of conduct, contribution files. **-0.5**

`src/.ipynb_checkpoints/` and `src/__pycache__/`

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I got an error while trying to run `make all`. **- 2.5**

You are missing your group package.

```
Quitting from lines 32-53 (Analysis_of_Investment_Outcomes_Report.rmd)
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ModuleNotFoundError: No module named 'group10pack'

Detailed traceback:
  File "<string>", line 1, in <module>
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
Calls: <Anonymous> ... py_capture_output -> force -> <Anonymous> -> py_call_impl

Execution halted
make: *** [Makefile:63: doc/Analysis_of_Investment_Outcomes_Report.pdf] Error 1
```

- [ ] I got an error while trying to install the group package. **- 2.5**

```
rstudio@74d39a7a54c0:~$ pip install group10pack
ERROR: Could not find a version that satisfies the requirement group10pack (from versions: none)
ERROR: No matching distribution found for group10pack
```

**Comment by GiuseppeTT** [comment]
Regraded as asked in a private message.
