### ISSUE TITLE
Setup file structure on develop

### ISSUE THREAD

**Issue by nkoda** [DSCI-310/DSCI-310-Group-10#3]
- [x] Add all necessary files for milestone one

**Comment by nkoda** [comment]
**File structure based on milestone1**
- [ ]README.md
- [ ] CODE_OF_CONDUCT.md
- [ ] CONTRIBUTING.md
- [ ] data/
- [ ] analysis.ipynb
- [ ] Dockerfile
- [ ] .github/workflows/publish_docker_image.yml
- [ ] LICENSE.md

**Comment by nkoda** [comment]
**Completed**
- all necessary files within the required milestone1 file structure has been initialized. 
- Data from stats-can suggested by Harry has been placed in data

**TODO**: 
- [ ] Fill in README.md
- [ ] Fill in CODE_OF_CONDUCT.md
- [ ] Fill in CONTRIBUTING.md
- [x] Load Data into data/
- [ ] Fill in analysis.ipynb
- [ ] Finish Dockerfile
- [ ] Finish github/workflows/publish_docker_image.yml
- [ ] Fill in LICENSE.md
