### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-10#37]
*Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### GitHub release

- [X] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION`
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone).
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

### Analysis (`.ipynb`) file

- [x] This document should not actually be named `analysis.ipynb`, but have a more descriptive title, related to the project title. **-1**

### Analysis methods & results

- [x] The data should be reproducibly downloaded from it's source using code in the analysis code document,
and a copy saved in the `data` directory (and ideally in the `data/raw` subdirectory. **-1**

### Dockerfile

- [x] The base image the `Dockerfile` uses in the `FROM` statement should have it's version pinned.
Failing to do this, means that each time the Docker image is built in the future,
the latest version of the base image will be used.
The latest version of the base image will very likely change over time,
and failing to do this will lead to the container not being able to be reproducibly built in the future. **-1**

### Project organization

- [x] The analysis notebook (`*.ipynb`) should be in a sub-directory called something sensible, such as `analysis`,
`src`, `notebooks`, `docs`, etc, to aid in the discoverability of this file, and related ones.
Having too many files in the project root makes the project organization less understandable
and can lead to longer activation times to productivity for collaborators (including future you!). **-1**
- [x] Files such as `.DS_Store` should not be committed. **-1**

### GitHub Issue Milestones

- [x] GitHub issue milestones were not used. **-5**

### CONTRIBUTING.md

- [x] Contributing documentation should reflect all the ways people can contribute to the project
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's,
as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-1**

### License

- [x] Creative commons license needs to be included to specify how non-code/software work can be used, shared and derived. **-2**

###  Analysis can be run reproducibly using documentation provided in the README

- [x] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**
- [x] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

### Team work contract

- [x] Team work contract missing. **-5**

**Comment by mahdiheydar** [comment]
### GitHub release

- Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION`
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone).
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

**the github release link was submitted in the form you indicated in the submission: [see here](https://github.com/DSCI-310/DSCI-310-Group-10/tree/v2.0.0)**

### Analysis (`.ipynb`) file

- This document should not actually be named `analysis.ipynb`, but have a more descriptive title, related to the project title. **-1**

**we changed the analysis document name to be more descriptive as evident in the root directory, the new name is Analysis_of_Investment_Outcome_Predictor.ipynb [see here](https://github.com/DSCI-310/DSCI-310-Group-10/tree/main/notebook)**

### Analysis methods & results

- The data should be reproducibly downloaded from it's source using code in the analysis code document,
and a copy saved in the `data` directory (and ideally in the `data/raw` subdirectory. **-1**

**Data directory was added to root directory with a data/raw and data/processed directories within [see here](https://github.com/DSCI-310/DSCI-310-Group-10/tree/main/data)**

### Dockerfile

- The base image the `Dockerfile` uses in the `FROM` statement should have it's version pinned.
Failing to do this, means that each time the Docker image is built in the future,
the latest version of the base image will be used.
The latest version of the base image will very likely change over time,
and failing to do this will lead to the container not being able to be reproducibly built in the future. **-1**

**The base image of the dockerfile has its version pinned as seen in the dockerfile - version 4.1.3 of the rocker/rstudio image was used [see here](https://github.com/DSCI-310/DSCI-310-Group-10/blob/main/Dockerfile)**
### Project organization

- The analysis notebook (`*.ipynb`) should be in a sub-directory called something sensible, such as `analysis`,
`src`, `notebooks`, `docs`, etc, to aid in the discoverability of this file, and related ones.
Having too many files in the project root makes the project organization less understandable
and can lead to longer activation times to productivity for collaborators (including future you!). **-1**
- Files such as `.DS_Store` should not be committed. **-1**

**Project files were organized with unnecessary files removed in root directory [see here](https://github.com/DSCI-310/DSCI-310-Group-10
)**

### GitHub Issue Milestones

- GitHub issue milestones were not used. **-5**

**Milestones were used for the remainder of the project [see here](https://github.com/DSCI-310/DSCI-310-Group-10/milestones?state=closed)**

### CONTRIBUTING.md

- Contributing documentation should reflect all the ways people can contribute to the project
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's,
as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-1**

**our contributions file was updated to be more descriptive of both outsiders roles and current project member roles [see here](https://github.com/DSCI-310/DSCI-310-Group-10/blob/main/CONTRIBUTING.md)**

### License

- Creative commons license needs to be included to specify how non-code/software work can be used, shared and derived. **-2**

**added creative commons license - please refer to very bottom of the README [see here](https://github.com/DSCI-310/DSCI-310-Group-10#readme)**

###  Analysis can be run reproducibly using documentation provided in the README

- Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**
- Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

**Usage documentation was improved for clarity as evident in the feedback received from peer review. Many peers were happy with the ease by which they could follow our instructions and run our analysis [feedback 1](https://github.com/DSCI-310/DSCI-310-Group-10/issues/94) and [feedback 2](https://github.com/DSCI-310/DSCI-310-Group-10/issues/93)**

**image version was added to instructions as well v3.59.0 [see here](https://github.com/DSCI-310/DSCI-310-Group-10/blob/main/README.md)**

### Team work contract

- Team work contract missing. **-5**

**team work contract was done just not submitted, here is the link for it once again [contract](https://docs.google.com/document/d/1gCm0GvOr58lh492O1L_0lT6UTaHKVEVVsffh2dGyZMI/edit?usp=sharing)**
