### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-10#70]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Helper data for tests is tractable and reproducible

- [x] There are cases of tests that recreate the output manually instead of using simple known input and output. **- 2**

`test_alpha_tunning` and `test_KNN_tunning`.

### Tests suite is of high quality

- [x] There are cases of functions that do not test at least 1 edge-case input. **- 4**

This happened in a lot of tests. An example of edge-case input is passing an empty list as an argument so that the input type is correct but the input value itself is not an expected value.

### Dependencies have been updated (so it include the test libraries)

- [x] Dependencie versions are not pinned. **- 1**

### GitHub Issue Milestones

- [X] ~~GitHub issue milestones were not used. **- 2**~~ **Edit: Regraded**

###  Analysis can be run reproducibly using documentation provided in the README

- [x] The git clone command does not work `git clone git@github.com:DSCI-310/DSCI-310-Group-10.git`, I had to use `git clone https://github.com/DSCI-310/DSCI-310-Group-10.git`. Check error below. **- 3**

```
Cloning into 'DSCI-310-Group-10'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

I would add explicitly commands on how to navigate to the cloned repository, both outside and inside the container.

**Comment by mahdiheydar** [comment]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Helper data for tests is tractable and reproducible

- There are cases of tests that recreate the output manually instead of using simple known input and output. **- 2**

`test_alpha_tunning` and `test_KNN_tunning`.

### Tests suite is of high quality

- There are cases of functions that do not test at least 1 edge-case input. **- 4**

**For test_alpha_tuning and test_KNN_tuning we cannot create a unique data set because each function needs **

This happened in a lot of tests. An example of edge-case input is passing an empty list as an argument so that the input type is correct but the input value itself is not an expected value.

### Dependencies have been updated (so it include the test libraries)

- Dependencie versions are not pinned. **- 1**

**all dependencies were pinned as seen in the requirements.txt file in the root directory [see here](https://github.com/DSCI-310/DSCI-310-Group-10/blob/main/requirements.txt)**

### GitHub Issue Milestones

- [X] ~~GitHub issue milestones were not used. **- 2**~~ **Edit: Regraded**

###  Analysis can be run reproducibly using documentation provided in the README

- [x] The git clone command does not work `git clone git@github.com:DSCI-310/DSCI-310-Group-10.git`, I had to use `git clone https://github.com/DSCI-310/DSCI-310-Group-10.git`. Check error below. **- 3**

```
Cloning into 'DSCI-310-Group-10'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**switched to ssh protocol in README instructions [see here](https://github.com/DSCI-310/DSCI-310-Group-10/blob/main/README.md)**

- Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**


I would add explicitly commands on how to navigate to the cloned repository, both outside and inside the container.

**image version was added to instructions as well v3.59.0 [see here](https://github.com/DSCI-310/DSCI-310-Group-10/blob/main/README.md)**
