### ISSUE TITLE
Considerations for Major Merge: milestone 3

### ISSUE THREAD

**Issue by nkoda** [DSCI-310/DSCI-310-Group-10#76]
TODOS: 
- [x] Restructure repo
- [x] Move all pickles to a temp folder, csv's to the data folder
- [x] Determine file order call
- [x] save figures to figures folder

Note: 
We should coordinate the script order for makefile
