### ISSUE TITLE
Data analysis review checklist

### ISSUE THREAD

**Issue by ClaudioETC** [DSCI-310/DSCI-310-Group-10#94]
### Conflict of interest

- [x] As the reviewer I confirm that I have no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [MDS code of conduct](https://ubc-mds.github.io/resources_pages/code_of_conduct/).

### General checks

- [x] **Repository:** Is the source code for this data analysis available? Is the repository well organized and easy to navigate?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

### Documentation

- [x] **Installation instructions:** Is there a clearly stated list of dependencies? 
- [x] **Example usage:** Do the authors include examples of how to use the software to reproduce the data analysis?
- [x] **Functionality documentation:** Is the core functionality of the data analysis software documented to a satisfactory level?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Code quality
- [] **Readability:** Are scripts, functions, objects, etc., well named? Is it relatively easy to understand the code?
- [x] **Style guidelides:** Does the code adhere to well known language style guides?
- [x] **Modularity:** Is the code suitably abstracted into scripts and functions?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified? Are they of sufficient quality to ensure software robsutness?

### Reproducibility
 
- [x] **Data:** Is the raw data archived somewhere? Is it accessible?
- [x] **Computational methods:** Is all the source code required for the data analysis available?
- [x] **Conditions:** Is there a record of the necessary conditions (software dependencies) needed to reproduce the analysis? Does there exist an easy way to obtain the computational environment needed to reproduce the analysis?
- [] **Automation:** Can someone other than the authors easily reproduce the entire data analysis?

### Analysis report

- [x] **Authors:** Does the report include a list of authors with their affiliations?
- [x] **What is the question:** Do the authors clearly state the research question being asked?
- [x] **Importance:** Do the authors clearly state the importance for this research question?
- [x] **Background**: Do the authors provide sufficient background information so that readers can understand the report?
- [ ] **Methods:** Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?
- [x] **Results:** Do the authors clearly communicate their findings through writing, tables and figures?
- [x] **Conclusions:** Are the conclusions presented by the authors correct? 
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Writing quality:** Is the writing of good quality, concise, engaging? 

### Review Comments: 

Please provide more detailed feedback here on what was done particularly well, and what could be improved. It is especially important to elaborate on items that you were not able to check off in the list above.

#### Attribution

###Well made points

I think it is a good project which lands well on the computational side. I found the functions and testing to be well developed and carefully thought. I think the project is well structured and the idea of the project was solid from the beginning. It seems like a project where everyone worked in a fluent way which lead to a project which does not seem as a "glue" of parts. The project is easy to deploy thanks to the well done README file, while the makefile was well developed with no errors in the process. The conclusions are solid.
Overall, I think the observations that have been mentioned will help improve to become an even better research paper (if it were the case).

###Points to improve

- I consider a Gitignore file could have been a good idea to avoid having some files I consider "non-essential" (ipyinb checkpoints can confuse readers which are not familiar with the difference between such file and the pure ".ipyinb" file.)
- I encountered some discrepancies when it came to the .html file: Some of the plots (histograms) differ from the ones I saw in the original .ipynb file. This confused me because in the beginning I did not know which plots to use as reference for what you were saying in the report. I also got mislead because I didn't understand the scale measurement in the x-axis because the variables were found confusing to understand, in some cases, which plot they had been assigned to.
- When it comes to the functions, I think you could have described them a bit more detailed, since I saw some functions inside /src/analysis/ that had the same description. Perhaps they are doing one big thing together, but then it should be specified what granular thing it is that they are doing. 
- I also think that in the beginning you could have described the Machine Learning/Data mining algorithms rather than just landing on them straight on. An introduction of those algorithms and how they work could be well appreciated.
- Another thing to consider is the number of branches that are still open. I recommend that you close them (if not used anymore) so that people don't get confused about their usage. 
- Las thing, and this might be my machine but when I ran it for the first time, it did not render the tex file successfully and therefore didn't handle the pdf version. I compiled the Tex file in Texmaker in my machine and then the pdf file showed up. I would suggest that you check out if the other reviewers had such problem (perhaps it could be my machine only, but I prefer to say it as something you might want to consider revisiting :) 

This was derived from the [JOSE review checklist](https://openjournals.readthedocs.io/en/jose/review_checklist.html) and the ROpenSci review checklist.
